// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJYJnfwMVbBV5Dwme2kB0ckGmMrpGLPA',
    appId: '1:897875643304:web:0333a68927f946db342b9d',
    messagingSenderId: '897875643304',
    projectId: 'crypto-tracker-48423',
    authDomain: 'crypto-tracker-48423.firebaseapp.com',
    storageBucket: 'crypto-tracker-48423.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqAKQrE4xCXKoYx21j0uAr2oc32t-xgI',
    appId: '1:897875643304:android:4e7cda4edf1bfcb6342b9d',
    messagingSenderId: '897875643304',
    projectId: 'crypto-tracker-48423',
    storageBucket: 'crypto-tracker-48423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRyFh0a4KxY2SrZNaCkwYT1IynSjJk5PA',
    appId: '1:897875643304:ios:b65d461e75e283a1342b9d',
    messagingSenderId: '897875643304',
    projectId: 'crypto-tracker-48423',
    storageBucket: 'crypto-tracker-48423.firebasestorage.app',
    iosBundleId: 'com.example.cryptoTracker',
  );
}
